source 'https://rubygems.org'

gem 'dotenv'
gem 'json'
gem 'pry'
gem 'rake'
gem 'sassc'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-static-assets'
gem 'sqlite3'
gem 'rackup'
gem 'puma'

group :development do
  gem 'foreman'
  gem 'rubocop'
  gem 'sqlite3'
end

group :test do
  gem 'rack-test'
  gem 'rspec', require: 'spec'
end
