source 'https://rubygems.org'

gem 'dotenv'
gem 'json'
gem 'pry'
gem 'puma'
gem 'rack-unreloader'
gem 'rackup'
gem 'rake'
gem 'sass-embedded'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'sinatra-static-assets'
gem 'sqlite3'

group :development do
  gem 'dawnscanner'
  gem 'foreman'
  gem 'rubocop'
end

group :test do
  gem 'rack-test'
  gem 'rspec', require: 'spec'
end
